### ISSUE TITLE
doc.title never set

### ISSUE THREAD

**Issue by chriswars** [juliandoucette/grunt-markdown-site#1]
Line 188 of tasks/site.js checks the typeof of doc.title but there is no code to set this (should be somewhere in loadDoc() ?)

This blocks every grunt run

https://github.com/juliandoucette/grunt-markdown-site/blob/70117f5cfd1cb37ca3b720eec11fc22dc33c0a95/tasks/site.js#L188

**Comment by juliandoucette** [comment]
Hi,

It's been a while.. (so I could be wrong / I can't make any promises but..)

I think doc gets title in it's definition above - like it gets all of it's
other front-matter properties. Unfortunatly I didn't document that
explicitly in code. But I did mention that title was required (in the
markdown front matter) here
https://github.com/juliandoucette/grunt-markdown-site#exporting

**Comment by chriswars** [comment]
Ahhh,I thought this "title" should be defined as a kind of "pagetitle" in the Grunt-Config, because i refered it to the declaration example in this file:

https://github.com/juliandoucette/grunt-markdown-site/blob/70117f5cfd1cb37ca3b720eec11fc22dc33c0a95/Gruntfile.js#L9

As a front-matter-property it works - thank you!
